package uk.ac.nottingham.create.stream;

/**
 * Enumerator for User and Status event types
 * 
 * @author pszjh
 */
public enum Event {
	TWEET,
	MENTION,
	RETWEET,
	FRIEND_RETWEET,
	FRIEND_OF_FRIEND_RETWEET,
	YOU_FAVOURITED,
	YOU_UNFAVOURITED,
	FAVOURITED_YOU,
	UNFAVOURITED_YOU,
	YOU_FOLLOWED,
	FOLLOWED_YOU,
	YOU_UNFOLLOWED,
		
	QUOTED_TWEET,
	RETWEETED_RETWEET,
	FAVOURITED_RETWEET,
	UNFOLLOWED_YOU,
	BLOCK,
	UNBLOCK,
	MESSAGE,
	MESSAGE_DELETION,
	STATUS
}
